language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng test --watch=false --browsers=ChromeHeadless --code-coverage
- ng build --prod --progress=false --base-href https://sticknitro.github.io/questionnaireio/
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/questionnaireio
  on:
    branch: master
